import json
from typing import Any

from core.settings import Settings
from models.schemas import AggregateMetrics, TranscriptResult
from pipeline.llm_prompts import GEMINI_SYSTEM_PROMPT

DOMAIN_KEYS = (
    "fluency_coherence",
    "lexical_resource",
    "grammatical_range_accuracy",
    "pronunciation",
)

DOMAIN_ITEM_KEYS = (
    "strength",
    "strength_evidence",
    "error",
    "error_evidence",
    "rubric_justification",
    "drill",
)


def _build_response_schema():
    from google.genai import types

    domain_item = types.Schema(
        type=types.Type.OBJECT,
        required=["strength", "strength_evidence", "error", "error_evidence", "rubric_justification", "drill"],
        properties={
            "strength": types.Schema(type=types.Type.STRING),
            "strength_evidence": types.Schema(type=types.Type.STRING),
            "error": types.Schema(type=types.Type.STRING),
            "error_evidence": types.Schema(type=types.Type.STRING),
            "rubric_justification": types.Schema(type=types.Type.STRING),
            "drill": types.Schema(type=types.Type.STRING),
        },
    )

    return types.Schema(
        type=types.Type.OBJECT,
        required=["summary", "domain_feedback"],
        properties={
            "summary": types.Schema(type=types.Type.STRING),
            "domain_feedback": types.Schema(
                type=types.Type.OBJECT,
                required=["fluency_coherence", "lexical_resource", "grammatical_range_accuracy", "pronunciation"],
                properties={
                    "fluency_coherence": domain_item,
                    "lexical_resource": domain_item,
                    "grammatical_range_accuracy": domain_item,
                    "pronunciation": domain_item,
                },
            ),
            "sample_rewrite": types.Schema(type=types.Type.STRING),
        },
    )


def _empty_domain_feedback() -> dict[str, dict[str, str]]:
    return {
        domain: {key: "" for key in DOMAIN_ITEM_KEYS}
        for domain in DOMAIN_KEYS
    }


def _normalize_narrative_payload(data: Any) -> dict[str, Any]:
    payload = data if isinstance(data, dict) else {}
    summary = payload.get("summary")
    sample_rewrite = payload.get("sample_rewrite")

    normalized_feedback = _empty_domain_feedback()
    feedback = payload.get("domain_feedback")
    if isinstance(feedback, dict):
        for domain in DOMAIN_KEYS:
            item = feedback.get(domain)
            if not isinstance(item, dict):
                continue
            for key in DOMAIN_ITEM_KEYS:
                value = item.get(key)
                normalized_feedback[domain][key] = str(value).strip() if value is not None else ""

    return {
        "summary": str(summary).strip() if summary is not None else "",
        "domain_feedback": normalized_feedback,
        "sample_rewrite": str(sample_rewrite).strip() if sample_rewrite is not None else "",
    }


def _fallback_payload() -> dict[str, Any]:
    return {
        "summary": (
            "Narrative AI feedback is temporarily unavailable. "
            "Numeric rubric scores are still generated by the deterministic scorer."
        ),
        "domain_feedback": _empty_domain_feedback(),
        "sample_rewrite": "",
    }


class GeminiEvaluator:
    def __init__(self, settings: Settings) -> None:
        if not settings.gemini_api_key:
            raise ValueError("GEMINI_API_KEY must be configured.")

        try:
            from google import genai
        except ImportError as exc:
            raise ImportError("google-genai package is required for Gemini evaluation.") from exc

        self.settings = settings
        self._client = genai.Client(api_key=settings.gemini_api_key)

    def evaluate(
        self,
        transcript: TranscriptResult,
        metrics: AggregateMetrics,
        fixed_scores: dict[str, float] | None = None,
    ) -> dict[str, Any]:
        from google.genai import types

        payload = {
            "transcript": transcript.text,
            "language": transcript.language,
            "metrics": metrics.model_dump(mode="json"),
        }
        if fixed_scores is not None:
            payload["fixed_scores"] = fixed_scores

        try:
            response = self._client.models.generate_content(
                model=self.settings.gemini_model,
                contents=json.dumps(payload, ensure_ascii=False),
                config=types.GenerateContentConfig(
                    system_instruction=GEMINI_SYSTEM_PROMPT,
                    response_mime_type="application/json",
                    response_schema=_build_response_schema(),
                    temperature=0,
                ),
            )

            if not response.text:
                return _fallback_payload()

            parsed = json.loads(response.text)
            return _normalize_narrative_payload(parsed)
        except Exception:
            return _fallback_payload()
